[2024-12-12T09:11:12.339-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: medallion_architecture.passo1 manual__2024-12-12T12:10:47.201328+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
