[2024-12-10T13:45:06.912-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: medallion_architecture.passo1 manual__2024-12-10T16:44:19.630051+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
